Update README.rst
Support-pp/Support-pp pull request #73
Opened 2021-02-22 07:03 UTC by nagasrihith608

Corrected a couple of punctuations.

2021-02-22 07:21 UTC, GamerBoomTV requested changes
Hello @nagasrihith608,
thanks for helping us to make our Support++ software better. 

There must be no teaching characters between the commands (!online / !offline). 

Thanks a lot.

Kind Regards,
Dan

2021-02-22 13:23 UTC, VerHext approved these changes

2021-02-22 13:29 UTC, Jniklas2 approved these changes

2021-02-22 13:32 UTC, esieben1310 approved these changes

2021-02-23 18:54 UTC, Lapotor requested changes
Please change as commented.

2021-02-23 18:54 UTC, Lapotor commented on README.rst
> +* Channel (name) renaming (! online /! offline)
Please remove the space between `!` and online and offline

2021-03-06 07:10 UTC, VerHext commented
Unfortunately, no change has been made to this branch for over 10 days. I close this pull request and reject the changes. Feel free to open a new one anytime.

2021-03-06 07:10 UTC, closed without merging