Changed to Team as owners
Support-pp/Support-pp pull request #74
Opened 2021-02-23 19:05 UTC by Lapotor

This change edits the Codeowners from @VerHext @Lapotor @GamerBoomTV to @Support-pp/reviewer and @Support-pp/developer.

2021-02-23 19:09 UTC, GamerBoomTV approved these changes

2021-02-23 19:16 UTC, VerHext requested changes
According to the docu and settings under team. There is a hardcoded limit of 3 reviewers per Team.
Commits to the Support++ main branch should be reviewed by all active team members. Currently 5.

2021-02-23 19:20 UTC, VerHext approved these changes
Okey, misunderstanding on my part.

2021-02-23 20:38 UTC, esieben1310 approved these changes

2021-02-24 20:45 UTC, Jniklas2 approved these changes

2021-02-24 20:47 UTC, merged